<script>
	export var document;

	import reference from '../reference';
	import {Transpiler} from '../lumio';

	var transpiler = new Transpiler(reference);

	var result;
	var code;

	//";; "+(document.name || 'untitled') + ".clar\n"
	var header = ";; Generated By Lumio (https://lumio.app)\n;; Date: "+(new Date())+"\n\n";

	$: result = transpiler.transpile(document);
	$: code = (header+(result.code || ';; Nothing to see here, time to create a smart contract.')).trim().split("\n");

</script>
<div id="code">
	<div class="gutter">
		{#each code as line, index}
			<div>{index}</div>
		{/each}
	</div>
	<div class="body">
		{#if code}
			{#each code as line}
				<code>{line || ' '}</code>
			{/each}
		{/if}
	</div>
	{#if result.problems && result.problems.length}
		<div class="problems">
			<p>Some problems were found with the code.</p>
			<ol>
				{#each result.problems as problem}
					<li>{problem.error}</li>
				{/each}
			</ol>
		</div>
	{/if}
</div>